/* Generated By:JJTree: Do not edit this line. ASTGenerated_variable_assignment.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Magenta.parser.generatednodes;

import .*;

public
class ASTGenerated_variable_assignment extends ASTNode {
  public ASTGenerated_variable_assignment(int id) {
    super(id);
  }

  public ASTGenerated_variable_assignment(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=47846808b039bbebb92512803e0cd26f (do not edit this line) */
