/* Generated By:JJTree: Do not edit this line. ASTGenerated_operator_addition.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Magenta.parser.generatednodes;

import .*;

public
class ASTGenerated_operator_addition extends ASTNode {
  public ASTGenerated_operator_addition(int id) {
    super(id);
  }

  public ASTGenerated_operator_addition(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=359577b9848a7aef4eca31786d59d871 (do not edit this line) */
