/* Generated By:JJTree: Do not edit this line. ASTGenerated_type.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Magenta.parser.generatednodes;

import .*;

public
class ASTGenerated_type extends ASTNode {
  public ASTGenerated_type(int id) {
    super(id);
  }

  public ASTGenerated_type(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bb4398ad6fc91693d958f3a3e9149ac2 (do not edit this line) */
