/* Generated By:JJTree: Do not edit this line. ASTGenerated_class_property_get.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Magenta.parser.generatednodes;

import .*;

public
class ASTGenerated_class_property_get extends ASTNode {
  public ASTGenerated_class_property_get(int id) {
    super(id);
  }

  public ASTGenerated_class_property_get(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=05fb641d573601d8e67ca5dc8b62b4b4 (do not edit this line) */
