/* Generated By:JJTree: Do not edit this line. ASTGenerated_operator_and.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Magenta.parser.generatednodes;

import .*;

public
class ASTGenerated_operator_and extends ASTNode {
  public ASTGenerated_operator_and(int id) {
    super(id);
  }

  public ASTGenerated_operator_and(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e5b6f7eb8df154b8b66da93d830bbd21 (do not edit this line) */
