/* Generated By:JJTree: Do not edit this line. ASTGenerated_operator_less_than.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Magenta.parser.generatednodes;

import .*;

public
class ASTGenerated_operator_less_than extends ASTNode {
  public ASTGenerated_operator_less_than(int id) {
    super(id);
  }

  public ASTGenerated_operator_less_than(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=991cf9ae9a5693f4ae68b3357b41cbc5 (do not edit this line) */
