/* Generated By:JJTree: Do not edit this line. ASTGenerated_data_type_boolean.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Magenta.parser.generatednodes;

import .*;

public
class ASTGenerated_data_type_boolean extends ASTNode {
  public ASTGenerated_data_type_boolean(int id) {
    super(id);
  }

  public ASTGenerated_data_type_boolean(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d65b53bb404572e8340c6b5298276510 (do not edit this line) */
