/* Generated By:JJTree: Do not edit this line. ASTGenerated_func_declartions.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Magenta.parser.generatednodes;

import .*;

public
class ASTGenerated_func_declartions extends ASTNode {
  public ASTGenerated_func_declartions(int id) {
    super(id);
  }

  public ASTGenerated_func_declartions(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4179cf6809149de0c9b8b0e631cd4f26 (do not edit this line) */
