/* Generated By:JJTree: Do not edit this line. ASTGenerated_operator_not.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Magenta.parser.generatednodes;

import .*;

public
class ASTGenerated_operator_not extends ASTNode {
  public ASTGenerated_operator_not(int id) {
    super(id);
  }

  public ASTGenerated_operator_not(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c29c4ee272c3a08b0b19ba68c4107e04 (do not edit this line) */
