/* Generated By:JJTree: Do not edit this line. ASTGenerated_parse.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Magenta.parser.generatednodes;

import .*;

public
class ASTGenerated_parse extends ASTNode {
  public ASTGenerated_parse(int id) {
    super(id);
  }

  public ASTGenerated_parse(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=151aca22fad8c269178d50d443a58c37 (do not edit this line) */
