/* Generated By:JJTree: Do not edit this line. ASTGenerated_operator_multiplication.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Magenta.parser.generatednodes;

import .*;

public
class ASTGenerated_operator_multiplication extends ASTNode {
  public ASTGenerated_operator_multiplication(int id) {
    super(id);
  }

  public ASTGenerated_operator_multiplication(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1ce77de01893fe5c0e69a0ee58fc67a5 (do not edit this line) */
