/* Generated By:JJTree: Do not edit this line. ASTGenerated_operator_greater_than.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Magenta.parser.generatednodes;

import .*;

public
class ASTGenerated_operator_greater_than extends ASTNode {
  public ASTGenerated_operator_greater_than(int id) {
    super(id);
  }

  public ASTGenerated_operator_greater_than(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=14bcff6476d5175ce96aa6a11695f6b2 (do not edit this line) */
