/* Generated By:JJTree: Do not edit this line. ASTGenerated_operator_modulous.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Magenta.parser.generatednodes;

import .*;

public
class ASTGenerated_operator_modulous extends ASTNode {
  public ASTGenerated_operator_modulous(int id) {
    super(id);
  }

  public ASTGenerated_operator_modulous(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e4cd400369daf405c31f1a42c3c49717 (do not edit this line) */
