/* Generated By:JJTree: Do not edit this line. ASTGenerated_expression_no_parenthesis.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Magenta.parser.generatednodes;

import .*;

public
class ASTGenerated_expression_no_parenthesis extends ASTNode {
  public ASTGenerated_expression_no_parenthesis(int id) {
    super(id);
  }

  public ASTGenerated_expression_no_parenthesis(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=38be3b338cb898fa01c4e8c18049f488 (do not edit this line) */
