/* Generated By:JJTree: Do not edit this line. ASTGenerated_statement_pass.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Magenta.parser.generatednodes;

import .*;

public
class ASTGenerated_statement_pass extends ASTNode {
  public ASTGenerated_statement_pass(int id) {
    super(id);
  }

  public ASTGenerated_statement_pass(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0d39978362127dd3b169ab53d4c130cf (do not edit this line) */
