/* Generated By:JJTree: Do not edit this line. ASTGenerated_variable_declarations.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Magenta.parser.generatednodes;

import .*;

public
class ASTGenerated_variable_declarations extends ASTNode {
  public ASTGenerated_variable_declarations(int id) {
    super(id);
  }

  public ASTGenerated_variable_declarations(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b9334b32c0b2f8948e6b05e6c4ad140a (do not edit this line) */
