/* Generated By:JJTree: Do not edit this line. ASTGenerated_data_type_decimal.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Magenta.parser.generatednodes;

import .*;

public
class ASTGenerated_data_type_decimal extends ASTNode {
  public ASTGenerated_data_type_decimal(int id) {
    super(id);
  }

  public ASTGenerated_data_type_decimal(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f4a6b488e6325422db5c91e54fef0979 (do not edit this line) */
