/* Generated By:JJTree: Do not edit this line. ASTGenerated_class_instantiation.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Magenta.parser.generatednodes;

import .*;

public
class ASTGenerated_class_instantiation extends ASTNode {
  public ASTGenerated_class_instantiation(int id) {
    super(id);
  }

  public ASTGenerated_class_instantiation(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ad5101f130061c3ab9c59651a1f80968 (do not edit this line) */
