/* Generated By:JJTree: Do not edit this line. ASTGenerated_expression_parenthesis.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Magenta.parser.generatednodes;

import .*;

public
class ASTGenerated_expression_parenthesis extends ASTNode {
  public ASTGenerated_expression_parenthesis(int id) {
    super(id);
  }

  public ASTGenerated_expression_parenthesis(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e0fd1c37b3f1b50620921e30cb1700d4 (do not edit this line) */
