/* Generated By:JJTree: Do not edit this line. ASTGenerated_variable_declaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Magenta.parser.generatednodes;

import .*;

public
class ASTGenerated_variable_declaration extends ASTNode {
  public ASTGenerated_variable_declaration(int id) {
    super(id);
  }

  public ASTGenerated_variable_declaration(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=018396d5bf51d3c9ca353195f07bffb9 (do not edit this line) */
