/* Generated By:JJTree: Do not edit this line. ASTGenerated_operator_subtraction.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Magenta.parser.generatednodes;

import .*;

public
class ASTGenerated_operator_subtraction extends ASTNode {
  public ASTGenerated_operator_subtraction(int id) {
    super(id);
  }

  public ASTGenerated_operator_subtraction(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7a246d8c00d0b6c8373e95333fd9da33 (do not edit this line) */
