/* Generated By:JJTree: Do not edit this line. ASTGenerated_operator_less_than_equal_to.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Magenta.parser.generatednodes;

import .*;

public
class ASTGenerated_operator_less_than_equal_to extends ASTNode {
  public ASTGenerated_operator_less_than_equal_to(int id) {
    super(id);
  }

  public ASTGenerated_operator_less_than_equal_to(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4b41ebdc5d65495c4e0d6f5a3ad005fb (do not edit this line) */
