/* Generated By:JJTree: Do not edit this line. ASTGenerated_statement_if.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Magenta.parser.generatednodes;

import .*;

public
class ASTGenerated_statement_if extends ASTNode {
  public ASTGenerated_statement_if(int id) {
    super(id);
  }

  public ASTGenerated_statement_if(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9fc39c7f9a4e45ad8ee57b3f17d2661a (do not edit this line) */
