package Magenta.parser.generatednodes;
import java.io.FileInputStream;

/* Generated By:JJTree&JavaCC: Do not edit this line. Parser.java */
import Magenta.parser.generatednodes.*;
import Parser.ParseException;
import Parser.SimpleCharStream;
import Parser.Token;



public class Parser/*@bgen(jjtree)*/implements ParserTreeConstants, ParserConstants {/*@bgen(jjtree)*/
  protected JJTParserState jjtree = new JJTParserState();public static void main(String[] args) {

        try {
            Parser parser = new Parser(new FileInputStream(args[0]));
            parser.parse();
            ((ASTNode) parser.jjtree.rootNode()).dump("   ");
            RuntimeNode.runRootNode((ASTNode) parser.jjtree.rootNode());
        } catch (Exception exception) {
            System.out.println("Something went wrong.");
            System.out.println("Exception: ");
            System.out.println(exception);
        }
    }

  final public void parse() throws ParseException {
    trace_call("parse");
    try {
               /*@bgen(jjtree) parse */
  ASTGenerated_parse jjtn000 = new ASTGenerated_parse(JJTPARSE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        label_1:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case IDENTCAPITALIZED:
          case KEYIF:
          case KEYWHILE:
          case KEYBLOCK:
          case KEYEMIT:
          case KEYTASK:
          case KEYPASS:
            ;
            break;
          default:
            jj_la1[0] = jj_gen;
            break label_1;
          }
          if (jj_2_1(2)) {
            class_declaration();
          } else if (jj_2_2(4)) {
            func_declaration();
          } else {
            switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
            case IDENTCAPITALIZED:
            case KEYIF:
            case KEYWHILE:
            case KEYEMIT:
            case KEYTASK:
            case KEYPASS:
              func_action();
              break;
            default:
              jj_la1[1] = jj_gen;
              jj_consume_token(-1);
              throw new ParseException();
            }
          }
        }
      } catch (Throwable jjte000) {
      if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
      } finally {
      if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
      }
    } finally {
      trace_return("parse");
    }
  }

  final public void func_action() throws ParseException {
    trace_call("func_action");
    try {
                     /*@bgen(jjtree) func_action */
  ASTGenerated_func_action jjtn000 = new ASTGenerated_func_action(JJTFUNC_ACTION);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        if (jj_2_5(2)) {
          variable_declaration();
          if (jj_2_3(2)) {

          } else {
            jj_consume_token(-1);
            throw new ParseException();
          }
          variable_assignment();
          if (jj_2_4(2)) {

          } else {
            jj_consume_token(-1);
            throw new ParseException();
          }
          class_method();
          jj_consume_token(PUNCSEMICOLON);
        } else {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case KEYTASK:
            func_call();
            jj_consume_token(PUNCSEMICOLON);
            break;
          case KEYIF:
          case KEYWHILE:
          case KEYEMIT:
          case KEYPASS:
            statements();
            switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
            case PUNCSEMICOLON:
              jj_consume_token(PUNCSEMICOLON);
              break;
            default:
              jj_la1[2] = jj_gen;
              ;
            }
            break;
          default:
            jj_la1[3] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
        }
      } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
      } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
      }
    } finally {
      trace_return("func_action");
    }
  }

  final public void func_actions() throws ParseException {
    trace_call("func_actions");
    try {
                      /*@bgen(jjtree) func_actions */
  ASTGenerated_func_actions jjtn000 = new ASTGenerated_func_actions(JJTFUNC_ACTIONS);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        label_2:
        while (true) {
          if (jj_2_6(2)) {
            ;
          } else {
            break label_2;
          }
          func_action();
        }
      } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
      } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
      }
    } finally {
      trace_return("func_actions");
    }
  }

  final public void func_declaration() throws ParseException {
    trace_call("func_declaration");
    try {
                          /*@bgen(jjtree) func_declaration */
  ASTGenerated_func_declaration jjtn000 = new ASTGenerated_func_declaration(JJTFUNC_DECLARATION);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        jj_consume_token(KEYTASK);
        identifier();
        jj_consume_token(PUNCLEFTPAREN);
        params();
        jj_consume_token(PUNCRIGHTPAREN);
        type();
        jj_consume_token(PUNCOPENARROW);
        func_action();
        jj_consume_token(PUNCCLOSEARROW);
      } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
      } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
      }
    } finally {
      trace_return("func_declaration");
    }
  }

  final public void param() throws ParseException {
    trace_call("param");
    try {
               /*@bgen(jjtree) param */
  ASTGenerated_param jjtn000 = new ASTGenerated_param(JJTPARAM);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        type();
        identifier();
      } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
      } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
      }
    } finally {
      trace_return("param");
    }
  }

  final public void params() throws ParseException {
    trace_call("params");
    try {
                /*@bgen(jjtree) params */
  ASTGenerated_params jjtn000 = new ASTGenerated_params(JJTPARAMS);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        label_3:
        while (true) {
          if (jj_2_7(2)) {
            ;
          } else {
            break label_3;
          }
          jj_consume_token(PUNCCOMMA);
          param();
        }
      } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
      } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
      }
    } finally {
      trace_return("params");
    }
  }

  final public void func_declartions() throws ParseException {
    trace_call("func_declartions");
    try {
                          /*@bgen(jjtree) func_declartions */
  ASTGenerated_func_declartions jjtn000 = new ASTGenerated_func_declartions(JJTFUNC_DECLARTIONS);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        label_4:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case KEYTASK:
            ;
            break;
          default:
            jj_la1[4] = jj_gen;
            break label_4;
          }
          func_declaration();
        }
      } catch (Throwable jjte000) {
   if (jjtc000) {
     jjtree.clearNodeScope(jjtn000);
     jjtc000 = false;
   } else {
     jjtree.popNode();
   }
   if (jjte000 instanceof RuntimeException) {
     {if (true) throw (RuntimeException)jjte000;}
   }
   if (jjte000 instanceof ParseException) {
     {if (true) throw (ParseException)jjte000;}
   }
   {if (true) throw (Error)jjte000;}
      } finally {
   if (jjtc000) {
     jjtree.closeNodeScope(jjtn000, true);
   }
      }
    } finally {
      trace_return("func_declartions");
    }
  }

  final public void class_declaration() throws ParseException {
    trace_call("class_declaration");
    try {
                           /*@bgen(jjtree) class_declaration */
  ASTGenerated_class_declaration jjtn000 = new ASTGenerated_class_declaration(JJTCLASS_DECLARATION);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        jj_consume_token(KEYBLOCK);
        type_name();
        jj_consume_token(PUNCOPENARROW);
        variable_assignments();
        variable_declarations();
        func_declartions();
        jj_consume_token(PUNCCLOSEARROW);
      } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
      } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
      }
    } finally {
      trace_return("class_declaration");
    }
  }

//instantiate a class
  final public void class_instantiation() throws ParseException {
    trace_call("class_instantiation");
    try {
                             /*@bgen(jjtree) class_instantiation */
  ASTGenerated_class_instantiation jjtn000 = new ASTGenerated_class_instantiation(JJTCLASS_INSTANTIATION);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        identifier();
        jj_consume_token(PUNCLEFTPAREN);
        values();
        jj_consume_token(PUNCRIGHTPAREN);
      } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
      } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
      }
    } finally {
      trace_return("class_instantiation");
    }
  }

//calling a method from a class
  final public void class_method() throws ParseException {
    trace_call("class_method");
    try {
                      /*@bgen(jjtree) class_method */
  ASTGenerated_class_method jjtn000 = new ASTGenerated_class_method(JJTCLASS_METHOD);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        identifier();
        jj_consume_token(PUNCPERIOD);
        func_call();
      } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
      } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
      }
    } finally {
      trace_return("class_method");
    }
  }

//get property of class
  final public void class_property_get() throws ParseException {
    trace_call("class_property_get");
    try {
                            /*@bgen(jjtree) class_property_get */
  ASTGenerated_class_property_get jjtn000 = new ASTGenerated_class_property_get(JJTCLASS_PROPERTY_GET);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        identifier();
        jj_consume_token(PUNCPERIOD);
        lowercase_identifier();
      } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
      } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
      }
    } finally {
      trace_return("class_property_get");
    }
  }

//calling a function
  final public void func_call() throws ParseException {
    trace_call("func_call");
    try {
                   /*@bgen(jjtree) func_call */
  ASTGenerated_func_call jjtn000 = new ASTGenerated_func_call(JJTFUNC_CALL);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        jj_consume_token(KEYTASK);
        identifier();
        jj_consume_token(PUNCLEFTPAREN);
        values();
        jj_consume_token(PUNCRIGHTPAREN);
      } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
      } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
      }
    } finally {
      trace_return("func_call");
    }
  }

//assign a variable
  final public void variable_assignment() throws ParseException {
    trace_call("variable_assignment");
    try {
                             /*@bgen(jjtree) variable_assignment */
  ASTGenerated_variable_assignment jjtn000 = new ASTGenerated_variable_assignment(JJTVARIABLE_ASSIGNMENT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        identifier();
        jj_consume_token(PUNCEQUALSIGN);
        value();
        jj_consume_token(PUNCSEMICOLON);
      } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
      } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
      }
    } finally {
      trace_return("variable_assignment");
    }
  }

//multiple variable assignments
  final public void variable_assignments() throws ParseException {
    trace_call("variable_assignments");
    try {
                              /*@bgen(jjtree) variable_assignments */
  ASTGenerated_variable_assignments jjtn000 = new ASTGenerated_variable_assignments(JJTVARIABLE_ASSIGNMENTS);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        label_5:
        while (true) {
          if (jj_2_8(2)) {
            ;
          } else {
            break label_5;
          }
          variable_assignment();
        }
      } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
      } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
      }
    } finally {
      trace_return("variable_assignments");
    }
  }

//declare a variable
  final public void variable_declaration() throws ParseException {
    trace_call("variable_declaration");
    try {
                              /*@bgen(jjtree) variable_declaration */
  ASTGenerated_variable_declaration jjtn000 = new ASTGenerated_variable_declaration(JJTVARIABLE_DECLARATION);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        type();
        identifier();
        jj_consume_token(PUNCEQUALSIGN);
        value();
        jj_consume_token(PUNCSEMICOLON);
      } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
      } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
      }
    } finally {
      trace_return("variable_declaration");
    }
  }

//declare multiple variables
  final public void variable_declarations() throws ParseException {
    trace_call("variable_declarations");
    try {
                               /*@bgen(jjtree) variable_declarations */
  ASTGenerated_variable_declarations jjtn000 = new ASTGenerated_variable_declarations(JJTVARIABLE_DECLARATIONS);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        label_6:
        while (true) {
          if (jj_2_9(2)) {
            ;
          } else {
            break label_6;
          }
          variable_declaration();
        }
      } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
      } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
      }
    } finally {
      trace_return("variable_declarations");
    }
  }

  final public void identifier() throws ParseException {
    trace_call("identifier");
    try {
                    /*@bgen(jjtree) identifier */
                     ASTGenerated_identifier jjtn000 = new ASTGenerated_identifier(JJTIDENTIFIER);
                     boolean jjtc000 = true;
                     jjtree.openNodeScope(jjtn000);Token t;
      try {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case IDENTUNDERSCORE:
          underscore_identifier();
          break;
        case IDENTLOWERCASE:
          lowercase_identifier();
          break;
        default:
          jj_la1[5] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
      } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
      }
    } finally {
      trace_return("identifier");
    }
  }

//holds the identifier (name) for functions and variables
  final public void underscore_identifier() throws ParseException {
    trace_call("underscore_identifier");
    try {
                               /*@bgen(jjtree) underscore_identifier */
                               ASTGenerated_underscore_identifier jjtn000 = new ASTGenerated_underscore_identifier(JJTUNDERSCORE_IDENTIFIER);
                               boolean jjtc000 = true;
                               jjtree.openNodeScope(jjtn000);Token t;
      try {
        t = jj_consume_token(IDENTUNDERSCORE);
          jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
          jjtn000.setFilteredValueForToken(t);
      } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
      }
    } finally {
      trace_return("underscore_identifier");
    }
  }

  final public void lowercase_identifier() throws ParseException {
    trace_call("lowercase_identifier");
    try {
                              /*@bgen(jjtree) lowercase_identifier */
                              ASTGenerated_lowercase_identifier jjtn000 = new ASTGenerated_lowercase_identifier(JJTLOWERCASE_IDENTIFIER);
                              boolean jjtc000 = true;
                              jjtree.openNodeScope(jjtn000);Token t;
      try {
        t = jj_consume_token(IDENTLOWERCASE);
          jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
          jjtn000.setFilteredValueForToken(t);
      } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
      }
    } finally {
      trace_return("lowercase_identifier");
    }
  }

  final public void type_name() throws ParseException {
    trace_call("type_name");
    try {
                   /*@bgen(jjtree) type_name */
                    ASTGenerated_type_name jjtn000 = new ASTGenerated_type_name(JJTTYPE_NAME);
                    boolean jjtc000 = true;
                    jjtree.openNodeScope(jjtn000);Token t;
      try {
        t = jj_consume_token(IDENTCAPITALIZED);
          jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
           jjtn000.setFilteredValueForToken(t);
      } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
      }
    } finally {
      trace_return("type_name");
    }
  }

  final public void type() throws ParseException {
    trace_call("type");
    try {
              /*@bgen(jjtree) type */
  ASTGenerated_type jjtn000 = new ASTGenerated_type(JJTTYPE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        if (jj_2_10(2)) {

        } else {
          jj_consume_token(-1);
          throw new ParseException();
        }
        type_name();
      } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
      } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
      }
    } finally {
      trace_return("type");
    }
  }

  final public void statements() throws ParseException {
    trace_call("statements");
    try {
                    /*@bgen(jjtree) statements */
  ASTGenerated_statements jjtn000 = new ASTGenerated_statements(JJTSTATEMENTS);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case KEYPASS:
          statement_pass();
          break;
        case KEYIF:
          statement_if();
          break;
        case KEYWHILE:
          statement_while();
          break;
        case KEYEMIT:
          statement_emit();
          break;
        default:
          jj_la1[6] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
      } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
      }
    } finally {
      trace_return("statements");
    }
  }

  final public void statement_pass() throws ParseException {
    trace_call("statement_pass");
    try {
                        /*@bgen(jjtree) statement_pass */
  ASTGenerated_statement_pass jjtn000 = new ASTGenerated_statement_pass(JJTSTATEMENT_PASS);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        jj_consume_token(KEYPASS);
        value();
      } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
      } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
      }
    } finally {
      trace_return("statement_pass");
    }
  }

  final public void statement_if() throws ParseException {
    trace_call("statement_if");
    try {
                      /*@bgen(jjtree) statement_if */
  ASTGenerated_statement_if jjtn000 = new ASTGenerated_statement_if(JJTSTATEMENT_IF);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        jj_consume_token(KEYIF);
        value();
        jj_consume_token(PUNCOPENARROW);
        jj_consume_token(PUNCCLOSEARROW);
      } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
      } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
      }
    } finally {
      trace_return("statement_if");
    }
  }

  final public void statement_while() throws ParseException {
    trace_call("statement_while");
    try {
                         /*@bgen(jjtree) statement_while */
  ASTGenerated_statement_while jjtn000 = new ASTGenerated_statement_while(JJTSTATEMENT_WHILE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        jj_consume_token(KEYWHILE);
        value();
        jj_consume_token(PUNCOPENARROW);
        jj_consume_token(PUNCCLOSEARROW);
      } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
      } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
      }
    } finally {
      trace_return("statement_while");
    }
  }

  final public void statement_emit() throws ParseException {
    trace_call("statement_emit");
    try {
                        /*@bgen(jjtree) statement_emit */
  ASTGenerated_statement_emit jjtn000 = new ASTGenerated_statement_emit(JJTSTATEMENT_EMIT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        jj_consume_token(KEYEMIT);
        value();
      } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
      } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
      }
    } finally {
      trace_return("statement_emit");
    }
  }

//basic data types of the programming language (decimal, integers, strings, and booleans)
  final public void data_type() throws ParseException {
    trace_call("data_type");
    try {
                   /*@bgen(jjtree) data_type */
                    ASTGenerated_data_type jjtn000 = new ASTGenerated_data_type(JJTDATA_TYPE);
                    boolean jjtc000 = true;
                    jjtree.openNodeScope(jjtn000);Token t;
      try {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case DECIMAL:
          data_type_decimal();
          break;
        case INTEGER:
          data_type_integer();
          break;
        case STRING:
          data_type_string();
          break;
        case BOOLEAN:
          data_type_boolean();
          break;
        default:
          jj_la1[7] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      } catch (Throwable jjte000) {
     if (jjtc000) {
       jjtree.clearNodeScope(jjtn000);
       jjtc000 = false;
     } else {
       jjtree.popNode();
     }
     if (jjte000 instanceof RuntimeException) {
       {if (true) throw (RuntimeException)jjte000;}
     }
     if (jjte000 instanceof ParseException) {
       {if (true) throw (ParseException)jjte000;}
     }
     {if (true) throw (Error)jjte000;}
      } finally {
     if (jjtc000) {
       jjtree.closeNodeScope(jjtn000, true);
     }
      }
    } finally {
      trace_return("data_type");
    }
  }

  final public void data_type_decimal() throws ParseException {
    trace_call("data_type_decimal");
    try {
                            /*@bgen(jjtree) data_type_decimal */
                             ASTGenerated_data_type_decimal jjtn000 = new ASTGenerated_data_type_decimal(JJTDATA_TYPE_DECIMAL);
                             boolean jjtc000 = true;
                             jjtree.openNodeScope(jjtn000);Token t;
      try {
        t = jj_consume_token(DECIMAL);
          jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
          jjtn000.setFilteredValueForToken(t);
      } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
      }
    } finally {
      trace_return("data_type_decimal");
    }
  }

  final public void data_type_integer() throws ParseException {
    trace_call("data_type_integer");
    try {
                            /*@bgen(jjtree) data_type_integer */
                             ASTGenerated_data_type_integer jjtn000 = new ASTGenerated_data_type_integer(JJTDATA_TYPE_INTEGER);
                             boolean jjtc000 = true;
                             jjtree.openNodeScope(jjtn000);Token t;
      try {
        t = jj_consume_token(INTEGER);
          jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
          jjtn000.setFilteredValueForToken(t);
      } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
      }
    } finally {
      trace_return("data_type_integer");
    }
  }

  final public void data_type_string() throws ParseException {
    trace_call("data_type_string");
    try {
                           /*@bgen(jjtree) data_type_string */
                            ASTGenerated_data_type_string jjtn000 = new ASTGenerated_data_type_string(JJTDATA_TYPE_STRING);
                            boolean jjtc000 = true;
                            jjtree.openNodeScope(jjtn000);Token t;
      try {
        t = jj_consume_token(STRING);
          jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
          jjtn000.setFilteredValueForToken(t);
      } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
      }
    } finally {
      trace_return("data_type_string");
    }
  }

  final public void data_type_boolean() throws ParseException {
    trace_call("data_type_boolean");
    try {
                            /*@bgen(jjtree) data_type_boolean */
                             ASTGenerated_data_type_boolean jjtn000 = new ASTGenerated_data_type_boolean(JJTDATA_TYPE_BOOLEAN);
                             boolean jjtc000 = true;
                             jjtree.openNodeScope(jjtn000);Token t;
      try {
        t = jj_consume_token(BOOLEAN);
          jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
          jjtn000.setFilteredValueForToken(t);
      } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
      }
    } finally {
      trace_return("data_type_boolean");
    }
  }

  final public void value() throws ParseException {
    trace_call("value");
    try {
               /*@bgen(jjtree) value */
  ASTGenerated_value jjtn000 = new ASTGenerated_value(JJTVALUE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        if (jj_2_11(3)) {
          expression_no_parenthesis();
        } else if (jj_2_12(3)) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case OPNOT:
            jj_consume_token(OPNOT);
            break;
          default:
            jj_la1[8] = jj_gen;
            ;
          }
          expression_parenthesis();
        } else if (jj_2_13(2)) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case OPNOT:
            jj_consume_token(OPNOT);
            break;
          default:
            jj_la1[9] = jj_gen;
            ;
          }
          data_type();
        } else if (jj_2_14(2)) {
          class_method();
        } else if (jj_2_15(2)) {
          class_property_get();
        } else if (jj_2_16(2)) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case OPNOT:
            jj_consume_token(OPNOT);
            break;
          default:
            jj_la1[10] = jj_gen;
            ;
          }
          func_call();
        } else if (jj_2_17(2)) {
          class_instantiation();
        } else if (jj_2_18(2)) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case OPNOT:
            jj_consume_token(OPNOT);
            break;
          default:
            jj_la1[11] = jj_gen;
            ;
          }
          identifier();
        } else {
          jj_consume_token(-1);
          throw new ParseException();
        }
      } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
      } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
      }
    } finally {
      trace_return("value");
    }
  }

  final public void values() throws ParseException {
    trace_call("values");
    try {
                /*@bgen(jjtree) values */
  ASTGenerated_values jjtn000 = new ASTGenerated_values(JJTVALUES);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        value();
        jj_consume_token(PUNCCOMMA);
        value();
      } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
      } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
      }
    } finally {
      trace_return("values");
    }
  }

  final public void val_no_expression_no_parenthesis() throws ParseException {
    trace_call("val_no_expression_no_parenthesis");
    try {
                                          /*@bgen(jjtree) val_no_expression_no_parenthesis */
  ASTGenerated_val_no_expression_no_parenthesis jjtn000 = new ASTGenerated_val_no_expression_no_parenthesis(JJTVAL_NO_EXPRESSION_NO_PARENTHESIS);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        if (jj_2_19(2)) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case OPNOT:
            jj_consume_token(OPNOT);
            break;
          default:
            jj_la1[12] = jj_gen;
            ;
          }
          expression_parenthesis();
        } else if (jj_2_20(2)) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case OPNOT:
            jj_consume_token(OPNOT);
            break;
          default:
            jj_la1[13] = jj_gen;
            ;
          }
          data_type();
        } else if (jj_2_21(2)) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case OPNOT:
            jj_consume_token(OPNOT);
            break;
          default:
            jj_la1[14] = jj_gen;
            ;
          }
          identifier();
        } else {
          jj_consume_token(-1);
          throw new ParseException();
        }
      } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
      } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
      }
    } finally {
      trace_return("val_no_expression_no_parenthesis");
    }
  }

  final public void val_no_expression() throws ParseException {
    trace_call("val_no_expression");
    try {
                           /*@bgen(jjtree) val_no_expression */
  ASTGenerated_val_no_expression jjtn000 = new ASTGenerated_val_no_expression(JJTVAL_NO_EXPRESSION);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        if (jj_2_22(2)) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case OPNOT:
            jj_consume_token(OPNOT);
            break;
          default:
            jj_la1[15] = jj_gen;
            ;
          }
          identifier();
        } else if (jj_2_23(2)) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case OPNOT:
            jj_consume_token(OPNOT);
            break;
          default:
            jj_la1[16] = jj_gen;
            ;
          }
          data_type();
        } else {
          jj_consume_token(-1);
          throw new ParseException();
        }
      } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
      } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
      }
    } finally {
      trace_return("val_no_expression");
    }
  }

  final public void expression_no_parenthesis() throws ParseException {
    trace_call("expression_no_parenthesis");
    try {
                                   /*@bgen(jjtree) expression_no_parenthesis */
  ASTGenerated_expression_no_parenthesis jjtn000 = new ASTGenerated_expression_no_parenthesis(JJTEXPRESSION_NO_PARENTHESIS);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        val_no_expression();
        label_7:
        while (true) {
          operators();
          val_no_expression_no_parenthesis();
          if (jj_2_24(2)) {
            ;
          } else {
            break label_7;
          }
        }
      } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
      } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
      }
    } finally {
      trace_return("expression_no_parenthesis");
    }
  }

  final public void expression_parenthesis() throws ParseException {
    trace_call("expression_parenthesis");
    try {
                                /*@bgen(jjtree) expression_parenthesis */
  ASTGenerated_expression_parenthesis jjtn000 = new ASTGenerated_expression_parenthesis(JJTEXPRESSION_PARENTHESIS);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        jj_consume_token(PUNCLEFTPAREN);
        val_no_expression_no_parenthesis();
        label_8:
        while (true) {
          operators();
          val_no_expression_no_parenthesis();
          if (jj_2_25(2)) {
            ;
          } else {
            break label_8;
          }
        }
        jj_consume_token(PUNCRIGHTPAREN);
      } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
      } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
      }
    } finally {
      trace_return("expression_parenthesis");
    }
  }

//used to detect the operator tokens used (addition, subtraction, multiplication, division, modulo, and logical operaters such as &&, ||, >=, <=, ==, etc) are all included
  final public void operators() throws ParseException {
    trace_call("operators");
    try {
                   /*@bgen(jjtree) operators */
                    ASTGenerated_operators jjtn000 = new ASTGenerated_operators(JJTOPERATORS);
                    boolean jjtc000 = true;
                    jjtree.openNodeScope(jjtn000);Token t;
      try {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case OPADD:
          jj_consume_token(OPADD);
          break;
        case OPSUBTRACT:
          jj_consume_token(OPSUBTRACT);
          break;
        case OPDIVIDE:
          jj_consume_token(OPDIVIDE);
          break;
        case OPMULTIPLY:
          jj_consume_token(OPMULTIPLY);
          break;
        case OPMODULO:
          jj_consume_token(OPMODULO);
          break;
        case OPEQUALTO:
          jj_consume_token(OPEQUALTO);
          break;
        case OPNOTEQUALTO:
          jj_consume_token(OPNOTEQUALTO);
          break;
        case OPGREATERTHAN:
          jj_consume_token(OPGREATERTHAN);
          break;
        case OPLESSTHAN:
          jj_consume_token(OPLESSTHAN);
          break;
        case OPGREATERTHANEQUALTO:
          jj_consume_token(OPGREATERTHANEQUALTO);
          break;
        case OPLESSTHANEQUALTO:
          jj_consume_token(OPLESSTHANEQUALTO);
          break;
        case OPAND:
          jj_consume_token(OPAND);
          break;
        case OPOR:
          jj_consume_token(OPOR);
          break;
        case OPNOT:
          jj_consume_token(OPNOT);
          break;
        default:
          jj_la1[17] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
      }
    } finally {
      trace_return("operators");
    }
  }

  private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  private boolean jj_2_5(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  private boolean jj_2_6(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_6(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  private boolean jj_2_7(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_7(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  private boolean jj_2_8(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_8(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  private boolean jj_2_9(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_9(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  private boolean jj_2_10(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_10(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(9, xla); }
  }

  private boolean jj_2_11(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_11(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(10, xla); }
  }

  private boolean jj_2_12(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_12(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(11, xla); }
  }

  private boolean jj_2_13(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_13(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(12, xla); }
  }

  private boolean jj_2_14(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_14(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(13, xla); }
  }

  private boolean jj_2_15(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_15(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(14, xla); }
  }

  private boolean jj_2_16(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_16(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(15, xla); }
  }

  private boolean jj_2_17(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_17(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(16, xla); }
  }

  private boolean jj_2_18(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_18(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(17, xla); }
  }

  private boolean jj_2_19(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_19(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(18, xla); }
  }

  private boolean jj_2_20(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_20(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(19, xla); }
  }

  private boolean jj_2_21(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_21(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(20, xla); }
  }

  private boolean jj_2_22(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_22(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(21, xla); }
  }

  private boolean jj_2_23(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_23(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(22, xla); }
  }

  private boolean jj_2_24(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_24(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(23, xla); }
  }

  private boolean jj_2_25(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_25(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(24, xla); }
  }

  private boolean jj_3R_27() {
    if (jj_3R_37()) return true;
    if (jj_3R_25()) return true;
    return false;
  }

  private boolean jj_3R_25() {
    if (jj_scan_token(IDENTCAPITALIZED)) return true;
    return false;
  }

  private boolean jj_3R_44() {
    if (jj_scan_token(IDENTLOWERCASE)) return true;
    return false;
  }

  private boolean jj_3R_43() {
    if (jj_scan_token(IDENTUNDERSCORE)) return true;
    return false;
  }

  private boolean jj_3R_36() {
    if (jj_3R_44()) return true;
    return false;
  }

  private boolean jj_3R_22() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_35()) {
    jj_scanpos = xsp;
    if (jj_3R_36()) return true;
    }
    return false;
  }

  private boolean jj_3R_35() {
    if (jj_3R_43()) return true;
    return false;
  }

  private boolean jj_3_9() {
    if (jj_3R_11()) return true;
    return false;
  }

  private boolean jj_3R_11() {
    if (jj_3R_27()) return true;
    if (jj_3R_22()) return true;
    return false;
  }

  private boolean jj_3R_23() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(13)) {
    jj_scanpos = xsp;
    if (jj_scan_token(14)) {
    jj_scanpos = xsp;
    if (jj_scan_token(16)) {
    jj_scanpos = xsp;
    if (jj_scan_token(15)) {
    jj_scanpos = xsp;
    if (jj_scan_token(17)) {
    jj_scanpos = xsp;
    if (jj_scan_token(18)) {
    jj_scanpos = xsp;
    if (jj_scan_token(19)) {
    jj_scanpos = xsp;
    if (jj_scan_token(20)) {
    jj_scanpos = xsp;
    if (jj_scan_token(21)) {
    jj_scanpos = xsp;
    if (jj_scan_token(22)) {
    jj_scanpos = xsp;
    if (jj_scan_token(23)) {
    jj_scanpos = xsp;
    if (jj_scan_token(24)) {
    jj_scanpos = xsp;
    if (jj_scan_token(25)) {
    jj_scanpos = xsp;
    if (jj_scan_token(26)) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3_8() {
    if (jj_3R_14()) return true;
    return false;
  }

  private boolean jj_3R_14() {
    if (jj_3R_22()) return true;
    if (jj_scan_token(PUNCEQUALSIGN)) return true;
    return false;
  }

  private boolean jj_3_25() {
    if (jj_3R_23()) return true;
    if (jj_3R_24()) return true;
    return false;
  }

  private boolean jj_3R_16() {
    if (jj_scan_token(PUNCLEFTPAREN)) return true;
    if (jj_3R_24()) return true;
    Token xsp;
    if (jj_3_25()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_25()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_20() {
    if (jj_scan_token(KEYTASK)) return true;
    if (jj_3R_22()) return true;
    return false;
  }

  private boolean jj_3R_19() {
    if (jj_3R_22()) return true;
    if (jj_scan_token(PUNCPERIOD)) return true;
    return false;
  }

  private boolean jj_3_24() {
    if (jj_3R_23()) return true;
    if (jj_3R_24()) return true;
    return false;
  }

  private boolean jj_3R_15() {
    if (jj_3R_30()) return true;
    Token xsp;
    if (jj_3_24()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_24()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_18() {
    if (jj_3R_22()) return true;
    if (jj_scan_token(PUNCPERIOD)) return true;
    return false;
  }

  private boolean jj_3R_21() {
    if (jj_3R_22()) return true;
    if (jj_scan_token(PUNCLEFTPAREN)) return true;
    return false;
  }

  private boolean jj_3_22() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(26)) jj_scanpos = xsp;
    if (jj_3R_22()) return true;
    return false;
  }

  private boolean jj_3R_30() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_22()) {
    jj_scanpos = xsp;
    if (jj_3_23()) return true;
    }
    return false;
  }

  private boolean jj_3_23() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(26)) jj_scanpos = xsp;
    if (jj_3R_17()) return true;
    return false;
  }

  private boolean jj_3R_9() {
    if (jj_scan_token(KEYBLOCK)) return true;
    if (jj_3R_25()) return true;
    return false;
  }

  private boolean jj_3_21() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(26)) jj_scanpos = xsp;
    if (jj_3R_22()) return true;
    return false;
  }

  private boolean jj_3_19() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(26)) jj_scanpos = xsp;
    if (jj_3R_16()) return true;
    return false;
  }

  private boolean jj_3R_24() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_19()) {
    jj_scanpos = xsp;
    if (jj_3_20()) {
    jj_scanpos = xsp;
    if (jj_3_21()) return true;
    }
    }
    return false;
  }

  private boolean jj_3_20() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(26)) jj_scanpos = xsp;
    if (jj_3R_17()) return true;
    return false;
  }

  private boolean jj_3_7() {
    if (jj_scan_token(PUNCCOMMA)) return true;
    if (jj_3R_13()) return true;
    return false;
  }

  private boolean jj_3R_26() {
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_7()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_13() {
    if (jj_3R_27()) return true;
    return false;
  }

  private boolean jj_3_18() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(26)) jj_scanpos = xsp;
    if (jj_3R_22()) return true;
    return false;
  }

  private boolean jj_3_17() {
    if (jj_3R_21()) return true;
    return false;
  }

  private boolean jj_3_16() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(26)) jj_scanpos = xsp;
    if (jj_3R_20()) return true;
    return false;
  }

  private boolean jj_3_15() {
    if (jj_3R_19()) return true;
    return false;
  }

  private boolean jj_3R_10() {
    if (jj_scan_token(KEYTASK)) return true;
    if (jj_3R_22()) return true;
    if (jj_scan_token(PUNCLEFTPAREN)) return true;
    if (jj_3R_26()) return true;
    if (jj_scan_token(PUNCRIGHTPAREN)) return true;
    return false;
  }

  private boolean jj_3_14() {
    if (jj_3R_18()) return true;
    return false;
  }

  private boolean jj_3_6() {
    if (jj_3R_12()) return true;
    return false;
  }

  private boolean jj_3_13() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(26)) jj_scanpos = xsp;
    if (jj_3R_17()) return true;
    return false;
  }

  private boolean jj_3R_53() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_11()) {
    jj_scanpos = xsp;
    if (jj_3_12()) {
    jj_scanpos = xsp;
    if (jj_3_13()) {
    jj_scanpos = xsp;
    if (jj_3_14()) {
    jj_scanpos = xsp;
    if (jj_3_15()) {
    jj_scanpos = xsp;
    if (jj_3_16()) {
    jj_scanpos = xsp;
    if (jj_3_17()) {
    jj_scanpos = xsp;
    if (jj_3_18()) return true;
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3_11() {
    if (jj_3R_15()) return true;
    return false;
  }

  private boolean jj_3_12() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(26)) jj_scanpos = xsp;
    if (jj_3R_16()) return true;
    return false;
  }

  private boolean jj_3R_42() {
    if (jj_scan_token(BOOLEAN)) return true;
    return false;
  }

  private boolean jj_3R_29() {
    if (jj_3R_38()) return true;
    return false;
  }

  private boolean jj_3R_28() {
    if (jj_3R_20()) return true;
    return false;
  }

  private boolean jj_3R_12() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_5()) {
    jj_scanpos = xsp;
    if (jj_3R_28()) {
    jj_scanpos = xsp;
    if (jj_3R_29()) return true;
    }
    }
    return false;
  }

  private boolean jj_3_5() {
    if (jj_3R_11()) return true;
    return false;
  }

  private boolean jj_3R_41() {
    if (jj_scan_token(STRING)) return true;
    return false;
  }

  private boolean jj_3_2() {
    if (jj_3R_10()) return true;
    return false;
  }

  private boolean jj_3R_40() {
    if (jj_scan_token(INTEGER)) return true;
    return false;
  }

  private boolean jj_3_1() {
    if (jj_3R_9()) return true;
    return false;
  }

  private boolean jj_3R_39() {
    if (jj_scan_token(DECIMAL)) return true;
    return false;
  }

  private boolean jj_3R_34() {
    if (jj_3R_42()) return true;
    return false;
  }

  private boolean jj_3R_33() {
    if (jj_3R_41()) return true;
    return false;
  }

  private boolean jj_3R_32() {
    if (jj_3R_40()) return true;
    return false;
  }

  private boolean jj_3R_17() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_31()) {
    jj_scanpos = xsp;
    if (jj_3R_32()) {
    jj_scanpos = xsp;
    if (jj_3R_33()) {
    jj_scanpos = xsp;
    if (jj_3R_34()) return true;
    }
    }
    }
    return false;
  }

  private boolean jj_3R_31() {
    if (jj_3R_39()) return true;
    return false;
  }

  private boolean jj_3R_52() {
    if (jj_scan_token(KEYEMIT)) return true;
    if (jj_3R_53()) return true;
    return false;
  }

  private boolean jj_3R_51() {
    if (jj_scan_token(KEYWHILE)) return true;
    if (jj_3R_53()) return true;
    return false;
  }

  private boolean jj_3R_50() {
    if (jj_scan_token(KEYIF)) return true;
    if (jj_3R_53()) return true;
    return false;
  }

  private boolean jj_3R_49() {
    if (jj_scan_token(KEYPASS)) return true;
    if (jj_3R_53()) return true;
    return false;
  }

  private boolean jj_3R_37() {
    return false;
  }

  private boolean jj_3R_46() {
    if (jj_3R_50()) return true;
    return false;
  }

  private boolean jj_3R_45() {
    if (jj_3R_49()) return true;
    return false;
  }

  private boolean jj_3R_38() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_45()) {
    jj_scanpos = xsp;
    if (jj_3R_46()) {
    jj_scanpos = xsp;
    if (jj_3R_47()) {
    jj_scanpos = xsp;
    if (jj_3R_48()) return true;
    }
    }
    }
    return false;
  }

  private boolean jj_3R_48() {
    if (jj_3R_52()) return true;
    return false;
  }

  private boolean jj_3R_47() {
    if (jj_3R_51()) return true;
    return false;
  }

  private boolean jj_3_4() {
    if (jj_scan_token(0)) return true;
    return false;
  }

  private boolean jj_3_3() {
    if (jj_scan_token(0)) return true;
    return false;
  }

  private boolean jj_3_10() {
    if (jj_scan_token(0)) return true;
    return false;
  }

  /** Generated Token Manager. */
  public ParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[18];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x400,0x400,0x20000000,0x0,0x0,0x1800,0x0,0x3c0,0x4000000,0x4000000,0x4000000,0x4000000,0x4000000,0x4000000,0x4000000,0x4000000,0x4000000,0x7ffe000,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x5e80,0x5a80,0x0,0x5a80,0x1000,0x0,0x4a80,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[25];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public Parser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Parser(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new ParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 18; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 18; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public Parser(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new ParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 18; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 18; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public Parser(ParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 18; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(ParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 18; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      trace_token(token, "");
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
      trace_token(token, " (in getNextToken)");
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[47];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 18; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 47; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  private int trace_indent = 0;
  private boolean trace_enabled = true;

/** Enable tracing. */
  final public void enable_tracing() {
    trace_enabled = true;
  }

/** Disable tracing. */
  final public void disable_tracing() {
    trace_enabled = false;
  }

  private void trace_call(String s) {
    if (trace_enabled) {
      for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
      System.out.println("Call:   " + s);
    }
    trace_indent = trace_indent + 2;
  }

  private void trace_return(String s) {
    trace_indent = trace_indent - 2;
    if (trace_enabled) {
      for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
      System.out.println("Return: " + s);
    }
  }

  private void trace_token(Token t, String where) {
    if (trace_enabled) {
      for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
      System.out.print("Consumed token: <" + tokenImage[t.kind]);
      if (t.kind != 0 && !tokenImage[t.kind].equals("\"" + t.image + "\"")) {
        System.out.print(": \"" + t.image + "\"");
      }
      System.out.println(" at line " + t.beginLine + " column " + t.beginColumn + ">" + where);
    }
  }

  private void trace_scan(Token t1, int t2) {
    if (trace_enabled) {
      for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
      System.out.print("Visited token: <" + tokenImage[t1.kind]);
      if (t1.kind != 0 && !tokenImage[t1.kind].equals("\"" + t1.image + "\"")) {
        System.out.print(": \"" + t1.image + "\"");
      }
      System.out.println(" at line " + t1.beginLine + " column " + t1.beginColumn + ">; Expected token: <" + tokenImage[t2] + ">");
    }
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 25; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
            case 5: jj_3_6(); break;
            case 6: jj_3_7(); break;
            case 7: jj_3_8(); break;
            case 8: jj_3_9(); break;
            case 9: jj_3_10(); break;
            case 10: jj_3_11(); break;
            case 11: jj_3_12(); break;
            case 12: jj_3_13(); break;
            case 13: jj_3_14(); break;
            case 14: jj_3_15(); break;
            case 15: jj_3_16(); break;
            case 16: jj_3_17(); break;
            case 17: jj_3_18(); break;
            case 18: jj_3_19(); break;
            case 19: jj_3_20(); break;
            case 20: jj_3_21(); break;
            case 21: jj_3_22(); break;
            case 22: jj_3_23(); break;
            case 23: jj_3_24(); break;
            case 24: jj_3_25(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
