/* Generated By:JJTree: Do not edit this line. ASTGenerated_data_type_integer.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Magenta.parser.generatednodes;

import .*;

public
class ASTGenerated_data_type_integer extends ASTNode {
  public ASTGenerated_data_type_integer(int id) {
    super(id);
  }

  public ASTGenerated_data_type_integer(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1487f739c0bbb7b51d18b2c090032137 (do not edit this line) */
