/* Generated By:JJTree: Do not edit this line. ASTGenerated_identifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Magenta.parser.generatednodes;

import .*;

public
class ASTGenerated_identifier extends ASTNode {
  public ASTGenerated_identifier(int id) {
    super(id);
  }

  public ASTGenerated_identifier(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=388301c153e19a452a86cf6baca51a92 (do not edit this line) */
