/* Generated By:JJTree: Do not edit this line. ASTGenerated_class_method.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Magenta.parser.generatednodes;

import .*;

public
class ASTGenerated_class_method extends ASTNode {
  public ASTGenerated_class_method(int id) {
    super(id);
  }

  public ASTGenerated_class_method(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c4819d1af1aba404ad761c6eda530ff8 (do not edit this line) */
