/* Generated By:JJTree: Do not edit this line. ASTGenerated_func_action.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Magenta.parser.generatednodes;

import .*;

public
class ASTGenerated_func_action extends ASTNode {
  public ASTGenerated_func_action(int id) {
    super(id);
  }

  public ASTGenerated_func_action(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=69db86a1cd255966874b3df3025516ae (do not edit this line) */
