/* Generated By:JJTree: Do not edit this line. ASTGenerated_underscore_identifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Magenta.parser.generatednodes;

import .*;

public
class ASTGenerated_underscore_identifier extends ASTNode {
  public ASTGenerated_underscore_identifier(int id) {
    super(id);
  }

  public ASTGenerated_underscore_identifier(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5ac3d8e773a18dfb4987056979a62468 (do not edit this line) */
