/* Generated By:JJTree: Do not edit this line. ASTGenerated_type_name.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Magenta.parser.generatednodes;

import .*;

public
class ASTGenerated_type_name extends ASTNode {
  public ASTGenerated_type_name(int id) {
    super(id);
  }

  public ASTGenerated_type_name(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=67701168bd4fb90055fedcdbbbe9eb51 (do not edit this line) */
