/* Generated By:JJTree: Do not edit this line. ASTGenerated_statement_while.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Magenta.parser.generatednodes;

import .*;

public
class ASTGenerated_statement_while extends ASTNode {
  public ASTGenerated_statement_while(int id) {
    super(id);
  }

  public ASTGenerated_statement_while(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9ed211a2dfd73f6eca1c07a07a27e075 (do not edit this line) */
