/* Generated By:JJTree: Do not edit this line. ASTGenerated_func_declaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Magenta.parser.generatednodes;

import .*;

public
class ASTGenerated_func_declaration extends ASTNode {
  public ASTGenerated_func_declaration(int id) {
    super(id);
  }

  public ASTGenerated_func_declaration(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=58b51e83880ee28fab875036f347cdc5 (do not edit this line) */
