/* Generated By:JJTree: Do not edit this line. ASTGenerated_param.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Magenta.parser.generatednodes;

import .*;

public
class ASTGenerated_param extends ASTNode {
  public ASTGenerated_param(int id) {
    super(id);
  }

  public ASTGenerated_param(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f024d31442a37674759ceab446d99867 (do not edit this line) */
