/* Generated By:JJTree: Do not edit this line. ASTGenerated_func_call.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Magenta.parser.generatednodes;

import .*;

public
class ASTGenerated_func_call extends ASTNode {
  public ASTGenerated_func_call(int id) {
    super(id);
  }

  public ASTGenerated_func_call(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4fb20ea15135b501f0380326186ccc06 (do not edit this line) */
