/* Generated By:JJTree: Do not edit this line. ASTGenerated_lowercase_identifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Magenta.parser.generatednodes;

import .*;

public
class ASTGenerated_lowercase_identifier extends ASTNode {
  public ASTGenerated_lowercase_identifier(int id) {
    super(id);
  }

  public ASTGenerated_lowercase_identifier(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ec5a84531d63059ca6a5c787c6d95334 (do not edit this line) */
