/* Generated By:JJTree: Do not edit this line. ASTGenerated_class_declaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Magenta.parser.generatednodes;

import .*;

public
class ASTGenerated_class_declaration extends ASTNode {
  public ASTGenerated_class_declaration(int id) {
    super(id);
  }

  public ASTGenerated_class_declaration(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2331b33ac257e6b9ec0c4f77c0ecf51e (do not edit this line) */
