/* Generated By:JJTree: Do not edit this line. ASTGenerated_val_no_expression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Magenta.parser.generatednodes;

import .*;

public
class ASTGenerated_val_no_expression extends ASTNode {
  public ASTGenerated_val_no_expression(int id) {
    super(id);
  }

  public ASTGenerated_val_no_expression(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=df1aec7183d5ac285f79353edbef5ee1 (do not edit this line) */
