/* Generated By:JJTree: Do not edit this line. ASTGenerated_variable_assignments.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Magenta.parser.generatednodes;

import .*;

public
class ASTGenerated_variable_assignments extends ASTNode {
  public ASTGenerated_variable_assignments(int id) {
    super(id);
  }

  public ASTGenerated_variable_assignments(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3cc938889158d534d0b96f1098046b4c (do not edit this line) */
