/* Generated By:JJTree: Do not edit this line. ASTGenerated_params.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Magenta.parser.generatednodes;

import .*;

public
class ASTGenerated_params extends ASTNode {
  public ASTGenerated_params(int id) {
    super(id);
  }

  public ASTGenerated_params(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5499d5a0035e91c37276d34190cbdb57 (do not edit this line) */
