package Parser;

/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 5.0 */
public interface ParserTreeConstants
{
  public int JJTPARSE = 0;
  public int JJTFUNC_ACTION = 1;
  public int JJTFUNC_ACTIONS = 2;
  public int JJTFUNC_DECLARATION = 3;
  public int JJTPARAM = 4;
  public int JJTPARAMS = 5;
  public int JJTFUNC_DECLARTIONS = 6;
  public int JJTCLASS_DECLARATION = 7;
  public int JJTCLASS_INSTANTIATION = 8;
  public int JJTCLASS_METHOD = 9;
  public int JJTCLASS_PROPERTY_GET = 10;
  public int JJTFUNC_CALL = 11;
  public int JJTVARIABLE_ASSIGNMENT = 12;
  public int JJTVARIABLE_ASSIGNMENTS = 13;
  public int JJTVARIABLE_DECLARATION = 14;
  public int JJTVARIABLE_DECLARATIONS = 15;
  public int JJTIDENTIFIER = 16;
  public int JJTUNDERSCORE_IDENTIFIER = 17;
  public int JJTLOWERCASE_IDENTIFIER = 18;
  public int JJTTYPE_NAME = 19;
  public int JJTTYPE = 20;
  public int JJTSTATEMENTS = 21;
  public int JJTSTATEMENT_PASS = 22;
  public int JJTSTATEMENT_IF = 23;
  public int JJTSTATEMENT_WHILE = 24;
  public int JJTSTATEMENT_EMIT = 25;
  public int JJTDATA_TYPE = 26;
  public int JJTDATA_TYPE_DECIMAL = 27;
  public int JJTDATA_TYPE_INTEGER = 28;
  public int JJTDATA_TYPE_STRING = 29;
  public int JJTDATA_TYPE_BOOLEAN = 30;
  public int JJTVALUE = 31;
  public int JJTVALUES = 32;
  public int JJTVAL_NO_EXPRESSION_NO_PARENTHESIS = 33;
  public int JJTVAL_NO_EXPRESSION = 34;
  public int JJTEXPRESSION_NO_PARENTHESIS = 35;
  public int JJTEXPRESSION_PARENTHESIS = 36;
  public int JJTOPERATORS = 37;


  public String[] jjtNodeName = {
    "parse",
    "func_action",
    "func_actions",
    "func_declaration",
    "param",
    "params",
    "func_declartions",
    "class_declaration",
    "class_instantiation",
    "class_method",
    "class_property_get",
    "func_call",
    "variable_assignment",
    "variable_assignments",
    "variable_declaration",
    "variable_declarations",
    "identifier",
    "underscore_identifier",
    "lowercase_identifier",
    "type_name",
    "type",
    "statements",
    "statement_pass",
    "statement_if",
    "statement_while",
    "statement_emit",
    "data_type",
    "data_type_decimal",
    "data_type_integer",
    "data_type_string",
    "data_type_boolean",
    "value",
    "values",
    "val_no_expression_no_parenthesis",
    "val_no_expression",
    "expression_no_parenthesis",
    "expression_parenthesis",
    "operators",
  };
}
/* JavaCC - OriginalChecksum=f365588eaf2b0e1fa6c7c7393b74fd62 (do not edit this line) */
