/* Generated By:JJTree: Do not edit this line. ASTGenerated_lowercase_identifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Parser.generatednodes;

import Parser.*;

public
class ASTGenerated_lowercase_identifier extends ASTNode {
  public ASTGenerated_lowercase_identifier(int id) {
    super(id);
  }

  public ASTGenerated_lowercase_identifier(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=01e4231e531c979e757e505514cfbf73 (do not edit this line) */
