/* Generated By:JJTree: Do not edit this line. ASTGenerated_statement_emit.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Parser.generatednodes;

import Parser.*;

public
class ASTGenerated_statement_emit extends ASTNode {
  public ASTGenerated_statement_emit(int id) {
    super(id);
  }

  public ASTGenerated_statement_emit(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f075bf6873e3909da60debd37224914c (do not edit this line) */
