/* Generated By:JJTree: Do not edit this line. ASTGenerated_params.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Parser.generatednodes;

import Parser.*;

public
class ASTGenerated_params extends ASTNode {
  public ASTGenerated_params(int id) {
    super(id);
  }

  public ASTGenerated_params(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3c6402c999c3aef8b8100ad560b9e593 (do not edit this line) */
