/* Generated By:JJTree: Do not edit this line. ASTGenerated_data_type_string.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Parser.generatednodes;

import Parser.*;

public
class ASTGenerated_data_type_string extends ASTNode {
  public ASTGenerated_data_type_string(int id) {
    super(id);
  }

  public ASTGenerated_data_type_string(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bf4b0fdd55a6e889bde297f8f4e9ebbe (do not edit this line) */
