/* Generated By:JJTree: Do not edit this line. ASTGenerated_value.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Parser.generatednodes;

import Parser.*;

public
class ASTGenerated_value extends ASTNode {
  public ASTGenerated_value(int id) {
    super(id);
  }

  public ASTGenerated_value(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0a75a467feb678de6932aaea27f46ac8 (do not edit this line) */
