/* Generated By:JJTree: Do not edit this line. ASTGenerated_func_declaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Parser.generatednodes;

import Parser.*;

public
class ASTGenerated_func_declaration extends ASTNode {
  public ASTGenerated_func_declaration(int id) {
    super(id);
  }

  public ASTGenerated_func_declaration(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=72279d874a079b93a01495d7b8985864 (do not edit this line) */
