/* Generated By:JJTree: Do not edit this line. ASTGenerated_func_declartions.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Parser.generatednodes;

import Parser.*;

public
class ASTGenerated_func_declartions extends ASTNode {
  public ASTGenerated_func_declartions(int id) {
    super(id);
  }

  public ASTGenerated_func_declartions(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1d98d32f647a553ad1f06ab8e5ec8b82 (do not edit this line) */
