/* Generated By:JJTree: Do not edit this line. ASTGenerated_func_call.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Parser.generatednodes;

import Parser.*;

public
class ASTGenerated_func_call extends ASTNode {
  public ASTGenerated_func_call(int id) {
    super(id);
  }

  public ASTGenerated_func_call(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ed42dc8fbeed2142283cdd52e683ae6b (do not edit this line) */
