/* Generated By:JJTree: Do not edit this line. ASTGenerated_class_method.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Parser.generatednodes;

import Parser.*;

public
class ASTGenerated_class_method extends ASTNode {
  public ASTGenerated_class_method(int id) {
    super(id);
  }

  public ASTGenerated_class_method(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=abd45030eaef1b41265900d52d7e07d0 (do not edit this line) */
