/* Generated By:JJTree: Do not edit this line. ASTGenerated_operator_greater_than.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Parser.generatednodes;

import Parser.*;

public
class ASTGenerated_operator_greater_than extends ASTNode {
  public ASTGenerated_operator_greater_than(int id) {
    super(id);
  }

  public ASTGenerated_operator_greater_than(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=310d64500c707c118a1dee370069606e (do not edit this line) */
