/* Generated By:JJTree: Do not edit this line. ASTGenerated_operator_less_than_equal_to.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Parser.generatednodes;

import Parser.*;

public
class ASTGenerated_operator_less_than_equal_to extends ASTNode {
  public ASTGenerated_operator_less_than_equal_to(int id) {
    super(id);
  }

  public ASTGenerated_operator_less_than_equal_to(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c6ead254820c57cd10b8808eb8478145 (do not edit this line) */
