/* Generated By:JJTree: Do not edit this line. ASTGenerated_type_name.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Parser.generatednodes;

import Parser.*;

public
class ASTGenerated_type_name extends ASTNode {
  public ASTGenerated_type_name(int id) {
    super(id);
  }

  public ASTGenerated_type_name(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6a4e34c892f065d4410fb27fe4518d2f (do not edit this line) */
