/* Generated By:JJTree: Do not edit this line. ASTGenerated_data_type_decimal.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Parser.generatednodes;

import Parser.*;

public
class ASTGenerated_data_type_decimal extends ASTNode {
  public ASTGenerated_data_type_decimal(int id) {
    super(id);
  }

  public ASTGenerated_data_type_decimal(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2227905587ec086dc9d3ca5a9a25baea (do not edit this line) */
