/* Generated By:JJTree: Do not edit this line. ASTGenerated_func_actions.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Parser.generatednodes;

import Parser.*;

public
class ASTGenerated_func_actions extends ASTNode {
  public ASTGenerated_func_actions(int id) {
    super(id);
  }

  public ASTGenerated_func_actions(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=577a71cab72199afb30d9d0c48c45247 (do not edit this line) */
