/* Generated By:JJTree: Do not edit this line. ASTGenerated_variable_assignment.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Parser.generatednodes;

import Parser.*;

public
class ASTGenerated_variable_assignment extends ASTNode {
  public ASTGenerated_variable_assignment(int id) {
    super(id);
  }

  public ASTGenerated_variable_assignment(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c772ea1710531b052b40145f42d2d62b (do not edit this line) */
