/* Generated By:JJTree: Do not edit this line. ASTGenerated_class_instantiation.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Parser.generatednodes;

import Parser.*;

public
class ASTGenerated_class_instantiation extends ASTNode {
  public ASTGenerated_class_instantiation(int id) {
    super(id);
  }

  public ASTGenerated_class_instantiation(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=47907ffeaa6847b58265d5565b393796 (do not edit this line) */
