/* Generated By:JJTree: Do not edit this line. ASTGenerated_statement_if.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Parser.generatednodes;

import Parser.*;

public
class ASTGenerated_statement_if extends ASTNode {
  public ASTGenerated_statement_if(int id) {
    super(id);
  }

  public ASTGenerated_statement_if(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=79d19fe05f64193276458b32b9af0822 (do not edit this line) */
