/* Generated By:JJTree: Do not edit this line. ASTGenerated_param.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Parser.generatednodes;

import Parser.*;

public
class ASTGenerated_param extends ASTNode {
  public ASTGenerated_param(int id) {
    super(id);
  }

  public ASTGenerated_param(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d7722f270744fdfb88513ea5857d12bd (do not edit this line) */
