/* Generated By:JJTree: Do not edit this line. ASTGenerated_operators.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Parser.generatednodes;

import Parser.*;

public
class ASTGenerated_operators extends ASTNode {
  public ASTGenerated_operators(int id) {
    super(id);
  }

  public ASTGenerated_operators(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3424550cc0ba271bc348934f9475074c (do not edit this line) */
