/* Generated By:JJTree: Do not edit this line. ASTGenerated_class_property_get.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Parser.generatednodes;

import Parser.*;

public
class ASTGenerated_class_property_get extends ASTNode {
  public ASTGenerated_class_property_get(int id) {
    super(id);
  }

  public ASTGenerated_class_property_get(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=389ae9b8e7f26be2bd6f8a2fbc4855a0 (do not edit this line) */
