/* Generated By:JJTree: Do not edit this line. ASTGenerated_parse.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Parser.generatednodes;

import Parser.*;

public
class ASTGenerated_parse extends ASTNode {
  public ASTGenerated_parse(int id) {
    super(id);
  }

  public ASTGenerated_parse(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3b038f015e62d6bd2a09b26f367ccbb3 (do not edit this line) */
