/* Generated By:JJTree: Do not edit this line. ASTGenerated_operator_not.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Parser.generatednodes;

import Parser.*;

public
class ASTGenerated_operator_not extends ASTNode {
  public ASTGenerated_operator_not(int id) {
    super(id);
  }

  public ASTGenerated_operator_not(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9e5b9ae7df567556624f1123689cc6de (do not edit this line) */
