/* Generated By:JJTree: Do not edit this line. ASTGenerated_func_action.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Parser.generatednodes;

import Parser.*;

public
class ASTGenerated_func_action extends ASTNode {
  public ASTGenerated_func_action(int id) {
    super(id);
  }

  public ASTGenerated_func_action(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b81dce8ea8bd468b5ea05e59e52d053e (do not edit this line) */
