/* Generated By:JJTree: Do not edit this line. ASTGenerated_val_no_expression_no_parenthesis.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Parser.generatednodes;

import Parser.*;

public
class ASTGenerated_val_no_expression_no_parenthesis extends ASTNode {
  public ASTGenerated_val_no_expression_no_parenthesis(int id) {
    super(id);
  }

  public ASTGenerated_val_no_expression_no_parenthesis(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=82be76680dfbaf181d927cab56a10cba (do not edit this line) */
