/* Generated By:JJTree: Do not edit this line. ASTGenerated_variable_declaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Parser.generatednodes;

import Parser.*;

public
class ASTGenerated_variable_declaration extends ASTNode {
  public ASTGenerated_variable_declaration(int id) {
    super(id);
  }

  public ASTGenerated_variable_declaration(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ef0adee08d6a9b918b780a08b50ebe01 (do not edit this line) */
