/* Generated By:JJTree: Do not edit this line. ASTGenerated_identifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Parser.generatednodes;

import Parser.*;

public
class ASTGenerated_identifier extends ASTNode {
  public ASTGenerated_identifier(int id) {
    super(id);
  }

  public ASTGenerated_identifier(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a12aa3a3e564758e151f19c2493142e5 (do not edit this line) */
