/* Generated By:JJTree: Do not edit this line. ASTGenerated_variable_assignments.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Parser.generatednodes;

import Parser.*;

public
class ASTGenerated_variable_assignments extends ASTNode {
  public ASTGenerated_variable_assignments(int id) {
    super(id);
  }

  public ASTGenerated_variable_assignments(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3b045dce3b3c070dfbb04207913c15d3 (do not edit this line) */
