/* Generated By:JJTree: Do not edit this line. ASTGenerated_values.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Parser.generatednodes;

import Parser.*;

public
class ASTGenerated_values extends ASTNode {
  public ASTGenerated_values(int id) {
    super(id);
  }

  public ASTGenerated_values(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=96267c51aee7897307ddee1f64e67404 (do not edit this line) */
