/* Generated By:JJTree: Do not edit this line. ASTGenerated_expression_parenthesis.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Parser.generatednodes;

import Parser.*;

public
class ASTGenerated_expression_parenthesis extends ASTNode {
  public ASTGenerated_expression_parenthesis(int id) {
    super(id);
  }

  public ASTGenerated_expression_parenthesis(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ac3f06f4931704f60bc48d168b84b376 (do not edit this line) */
