/* Generated By:JJTree: Do not edit this line. ASTGenerated_val_no_expression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Parser.generatednodes;

import Parser.*;

public
class ASTGenerated_val_no_expression extends ASTNode {
  public ASTGenerated_val_no_expression(int id) {
    super(id);
  }

  public ASTGenerated_val_no_expression(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d707a5aa18a7269b7b8167c30e3efbfe (do not edit this line) */
