/* Generated By:JJTree: Do not edit this line. ASTGenerated_operator_multiplication.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Parser.generatednodes;

import Parser.*;

public
class ASTGenerated_operator_multiplication extends ASTNode {
  public ASTGenerated_operator_multiplication(int id) {
    super(id);
  }

  public ASTGenerated_operator_multiplication(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6b2325ba6181012ed36c6b6fa3bcacd7 (do not edit this line) */
