/* Generated By:JJTree: Do not edit this line. ASTGenerated_statement_pass.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Parser.generatednodes;

import Parser.*;

public
class ASTGenerated_statement_pass extends ASTNode {
  public ASTGenerated_statement_pass(int id) {
    super(id);
  }

  public ASTGenerated_statement_pass(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c3ad1a2d624930ea4c9316105b926ef5 (do not edit this line) */
