/* Generated By:JJTree: Do not edit this line. ASTGenerated_statements.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Parser.generatednodes;

import Parser.*;

public
class ASTGenerated_statements extends ASTNode {
  public ASTGenerated_statements(int id) {
    super(id);
  }

  public ASTGenerated_statements(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=736d0b1e2a4c9d158e362693e71f4f68 (do not edit this line) */
