/* Generated By:JJTree: Do not edit this line. ASTGenerated_data_type.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Parser.generatednodes;

import Parser.*;

public
class ASTGenerated_data_type extends ASTNode {
  public ASTGenerated_data_type(int id) {
    super(id);
  }

  public ASTGenerated_data_type(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fd50edc58a956826bddbbeb947eab567 (do not edit this line) */
