/* Generated By:JJTree: Do not edit this line. ASTGenerated_operator_modulous.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Parser.generatednodes;

import Parser.*;

public
class ASTGenerated_operator_modulous extends ASTNode {
  public ASTGenerated_operator_modulous(int id) {
    super(id);
  }

  public ASTGenerated_operator_modulous(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fe80519a6cb37e8d5a5e2026558a3865 (do not edit this line) */
