/* Generated By:JJTree: Do not edit this line. ASTGenerated_class_declaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Parser.generatednodes;

import Parser.*;

public
class ASTGenerated_class_declaration extends ASTNode {
  public ASTGenerated_class_declaration(int id) {
    super(id);
  }

  public ASTGenerated_class_declaration(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7ca477471d0693107bbd6d2d3a56aa8b (do not edit this line) */
