/* Generated By:JJTree: Do not edit this line. ASTGenerated_operator_and.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Parser.generatednodes;

import Parser.*;

public
class ASTGenerated_operator_and extends ASTNode {
  public ASTGenerated_operator_and(int id) {
    super(id);
  }

  public ASTGenerated_operator_and(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=65deff623e62c7f760a19c20307c3f30 (do not edit this line) */
