/* Generated By:JJTree: Do not edit this line. ASTGenerated_operator_subtraction.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Parser.generatednodes;

import Parser.*;

public
class ASTGenerated_operator_subtraction extends ASTNode {
  public ASTGenerated_operator_subtraction(int id) {
    super(id);
  }

  public ASTGenerated_operator_subtraction(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=619f2739a20aaf4161daf40436d6aca1 (do not edit this line) */
