/* Generated By:JJTree: Do not edit this line. ASTGenerated_operator_division.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Parser.generatednodes;

import Parser.*;

public
class ASTGenerated_operator_division extends ASTNode {
  public ASTGenerated_operator_division(int id) {
    super(id);
  }

  public ASTGenerated_operator_division(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=47f50a574e6798e6aab202c9d9c65738 (do not edit this line) */
