/* Generated By:JJTree: Do not edit this line. ASTGenerated_underscore_identifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Parser.generatednodes;

import Parser.*;

public
class ASTGenerated_underscore_identifier extends ASTNode {
  public ASTGenerated_underscore_identifier(int id) {
    super(id);
  }

  public ASTGenerated_underscore_identifier(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=95c2e480f4f118f82de9804aca7553ff (do not edit this line) */
