/* Generated By:JJTree: Do not edit this line. ASTGenerated_statement_while.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=ASTGenerated_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Parser.generatednodes;

import Parser.*;

public
class ASTGenerated_statement_while extends ASTNode {
  public ASTGenerated_statement_while(int id) {
    super(id);
  }

  public ASTGenerated_statement_while(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d1b67bdb6d49b4c14185b90cba794b4a (do not edit this line) */
